//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.16 at 12:38:39 AM AEDT 
//


package dev.toke.components;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ComponentDetails" type="{http://www.toke.dev/components}ComponentDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentDetails"
})
@XmlRootElement(name = "ComponentResponse")
public class ComponentResponse {

    @XmlElement(name = "ComponentDetails", required = true)
    protected ComponentDetails componentDetails;

    /**
     * Gets the value of the componentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentDetails }
     *     
     */
    public ComponentDetails getComponentDetails() {
        return componentDetails;
    }

    /**
     * Sets the value of the componentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentDetails }
     *     
     */
    public void setComponentDetails(ComponentDetails value) {
        this.componentDetails = value;
    }

}
